### ISSUE TITLE
Reset: draw inspiration from hacknug's

### ISSUE THREAD

**Issue by benface** [benface/tailwindcss-config#18]
From https://gist.github.com/hacknug/53ff40d9a9c905f98de0f43e53650cb3

```
input, textarea, button {
    text-align: inherit;
    text-transform: inherit;
    letter-spacing: inherit;
}
```

```
small {
  font: inherit;
}
```

**Comment by benface** [comment]
Actually `small` being `font-size: smaller` by default makes sense, just like `b` and `strong` are set to `font-weight: bolder` by Normalize.

**Comment by hacknug** [comment]
It actually doesn't according to the spec:
> In HTML5, this element is repurposed to represent side-comments and small print, including copyright and legal text, independent of its styled presentation.

`small` has a pretty specific semantic meaning and it shouldn't be used to make things smaller at all imho. Also, your config file so you can do whatever you want, just felt like leaving my two cents since I saw this 😄

**Comment by benface** [comment]
@hacknug You're right, of course :) Thank you!
