### ISSUE TITLE
Add a utility for `background-size: 100% 100%`

### ISSUE THREAD

**Issue by benface** [benface/tailwindcss-config#25]
`bg-stretch`?

**Comment by hacknug** [comment]
`.bg-fill` since it would be the equivalent to `object-fit: fill`?

**Comment by benface** [comment]
@hacknug Well spotted! I feel like `stretch` conveys the idea that the image is stretched with no regard for its aspect ratio better than `fill` (`cover` fills the container as well!), but since it's an official CSS term, I'll probably go with that. Made me wonder why `fill` doesn't exist as a keyword for `background-size`, and I ended up suggesting it here: https://github.com/w3c/csswg-drafts/issues/4117

**Comment by hacknug** [comment]
Agree with `stretch` conveying purpose better but still I think it's always better to mirror the spec. Makes it easier for new people using Tailwind and helps current users familiarize with CSS' nomenclature.

EDIT: Following your issue in w3c/csswg-drafts 👍
