### ISSUE TITLE
Add `extendVariants` option

### ISSUE THREAD

**Issue by benface** [benface/tailwindcss-config#32]
To be able to add variants for a given property, without having to re-specify all of them.

**Comment by hacknug** [comment]
I've also been thinking about it lately. Could this be solved with the config options introduced for the plugins API in v1.2? Should we make this a core thing maybe? It's somewhat annoying having to look what the default variants are for each core plugin…

**Comment by benface** [comment]
> Could this be solved with the config options introduced for the plugins API in v1.2?

I don't think so but I could be wrong.

> Should we make this a core thing maybe?

Well, your own argument against it [in this issue](https://github.com/tailwindcss/tailwindcss/issues/1148) is pretty solid, haha. But yeah, when the order doesn't matter (it doesn't in many cases) this would make sense IMO.

**Comment by hacknug** [comment]
Oh crap, forgot about order. Should never do this things when I've been drinking haha
